### ISSUE TITLE
Location marker changes position while zooming or maneuvering through map

### ISSUE THREAD

**Issue by TheBango** [manticorp/unrealheightmap#8]
By now the location marker changes its position if you try to zoom in/out using the mouse wheel or the arrows in the "Zoom" input box.
The only way to keep the position is by typing in the desired zoom level manually.

The location marker also changes position if you try to maneuver through map by press & hold the mouse wheel button and then moving the mouse.

Solution:
User should only be able to set the location by click on left mouse button and the location marker then should stay fix on this position until another click on left mouse button has occurred.

**Comment by manticorp** [comment]
Thank you for suggesting this! luckily this is built in to leaflet 👍 

This is now fixed with commit #4b66c965b2c142a6e6e49eadccfa6c54288d82e1

**Comment by TheBango** [comment]
Unfortunately, the issue still occurs. 
Try it yourself with the following steps: 
1. Choose a location with a crossroad, zoom in to max level and set the location marker to be in the middle of the crossroad.
2. Then zoom out as far as possible and then zoom in again.
3. You'll see that the location marker has changed its position.

> The location marker also changes position if you try to maneuver through map by press & hold the mouse wheel button and then moving the mouse.

This issue still appears, too.
